In [1]:
# Data = systematic record of particular quantity. 

In [2]:
# Numpy package 
# Numpy = Numerical Python
# working method = arrays 

In [3]:
# import 
# install 

In [4]:
# import = some packages are pre-installed. 
# install = first install then import 

In [5]:
import numpy as np

In [6]:
#1D Array Using Numpy 

a = np.array([10,20,30,40,50])

In [7]:
print(a)

[10 20 30 40 50]


In [8]:
# 4 different ways/functions to create 1D array in Numpy.

In [9]:
# Way 1 - Using Array Function 

import numpy as np 
b = np.array([2,4,6,8,10])
print(b)

[ 2  4  6  8 10]


In [10]:

import numpy as np 
c = np.array([2,4,6.50,8,10])
print(c)

[ 2.   4.   6.5  8.  10. ]


In [11]:
# Way 2 - linspace Function #(start,stop,N)

import numpy as np
b =np.linspace(2,4,6,8,10)
print(b)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. ]), 0.4)


In [14]:
# Way 3 - arange Function #(start,stop,stepsize)

import numpy as np

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
import numpy as np

a = np.arange(5,10)
print(a)

[5 6 7 8 9]


In [16]:
# Way 4 - ones() and zeros() function 

import numpy as np
K =np.zeros(5)
print(K)

[0. 0. 0. 0. 0.]


In [17]:
import numpy as np 
R = np.ones(5)
print(R)

[1. 1. 1. 1. 1.]


In [18]:
# Mathematical Operations on Arrays 

import numpy as np
K =np.array([10,20,30,40,50])
print(K)

[10 20 30 40 50]


In [19]:
K + 5

array([15, 25, 35, 45, 55])

In [20]:
K - 5

array([ 5, 15, 25, 35, 45])

In [27]:
K*5

array([ 50, 100, 150, 200, 250])

In [22]:
K/5

array([ 2.,  4.,  6.,  8., 10.])

In [23]:
# All science is data science. 

In [24]:
# 2D Array Creation Using Numpy 

import numpy as np 
X = np.array([[2,4,6],[6,8,10]])
print(X)

[[ 2  4  6]
 [ 6  8 10]]


In [26]:
# ndim Attribute 
A = np.array([5,6,7,9])
B = np.array([[2,4,6],[6,8,10]])
print(A.ndim) # Number of Rows in Array A 
print(B.ndim) # Number of Rows in Array B

1
2


In [28]:
# shape Attribute 

import numpy as np
K = np.array([1,2,3,4,5]) # For 1D array, number of elements 

In [29]:
print(K.shape)

(5,)


In [30]:
import numpy as np 
X = np.array([[2,4,6],[6,8,10]]) # For 2D array, number of rows and columns

In [32]:
print(X.shape)

(2, 3)


In [33]:
# size attribute # total number of elements in the array 

A = np.array([5,6,7,9])
print(A.size)

4


In [34]:
B = np.array([[2,4,6],[6,8,10]])
print(B.size)

6


In [35]:
# reshape method (to change the shape of the array)

import numpy as np 
D = np.array([[4,5,6,7],[5,6,7,8],[7,8,9,10]])
print(D)

[[ 4  5  6  7]
 [ 5  6  7  8]
 [ 7  8  9 10]]


In [36]:
print(D.shape) # (rows, columns)

(3, 4)


In [37]:
# reshape into (6,2)

D1 = D.reshape(6,2)

In [38]:
print(D1)

[[ 4  5]
 [ 6  7]
 [ 5  6]
 [ 7  8]
 [ 7  8]
 [ 9 10]]


In [39]:
# Joins in Array 

# concatenate() - to join more than one array conditon : array = same shape

import numpy as np
a = np.array([2,3,4,50])
b = ([8,9,10,11,15])
c = np.concatenate([a,b])
print(c)

[ 2  3  4 50  8  9 10 11 15]


In [41]:
# hstack - to join more than one array horizontally or row wise 

import numpy as np 
a = np.array([1,2,3])
b = np.array([10,11,12])
c = np.hstack((a,b))
print(c)

[ 1  2  3 10 11 12]


In [42]:
# vstack - to join more than one array vertically or column wise

import numpy as np 
a = np.array([1,2,3])
b = np.array([10,11,12])
c = np.vstack((a,b))
print(c)

[[ 1  2  3]
 [10 11 12]]


In [43]:
# Split function equal/unequal

import numpy as np
x =[1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5]) # split the array into 3 subsets - [0:3],[3:5],[5:] # indices between 3 and 5
# first sub-array  - elements before index 3 (0,1,2)
# second sub-array = elements between indices 3 and 5 
# third sub-array = elements after index 5 
# Index 3 = 4th elements in the array 

print(x1,x2,x3)


[1 2 3] [99 99] [3 2 1]
